// Generated by scripts/build-avatar-catalog.js.
module.exports = [
  {
    "id": "hiyori",
    "name": "日和 · Hiyori",
    "family": "默认角色",
    "builtIn": true,
    "preview": {
      "cloudPath": "ning/avatars/v1/hiyori/0c5ee185348c/preview.png",
      "size": 33762,
      "sha1": "0c5ee185348c412984a3371047ce70ae26d7fd82"
    },
    "localPreview": "/packages/avatars/previews/hiyori.jpg"
  },
  {
    "id": "local-57e8504a0d5b",
    "name": "Zara",
    "family": "碧蓝航线",
    "version": "5659889bf523",
    "model": {
      "cloudPath": "ning/avatars/v1/local-57e8504a0d5b/5659889bf523/model.moc3",
      "size": 1000896,
      "sha1": "b94e14a8682ca0d8e16fd7643a359d56de74125b"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-57e8504a0d5b/5659889bf523/texture-0.png",
        "size": 4364168,
        "sha1": "67df7022b16c1130dcb65f02ed5a57977c544edf"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-57e8504a0d5b/5659889bf523/preview.png",
      "size": 119497,
      "sha1": "c75948d7eefcfadfec94cb12aa225ca891b567cf"
    },
    "localPreview": "/packages/avatars/previews/local-57e8504a0d5b.jpg"
  },
  {
    "id": "local-85f25624f5c3",
    "name": "Atago (Midsummer March)",
    "family": "碧蓝航线",
    "version": "fa94e72d4348",
    "model": {
      "cloudPath": "ning/avatars/v1/local-85f25624f5c3/fa94e72d4348/model.moc3",
      "size": 1226944,
      "sha1": "1740ae76c36a4ac8582655edfa92edc48dec4fc0"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-85f25624f5c3/fa94e72d4348/texture-0.png",
        "size": 2950490,
        "sha1": "b99e32ec24cc40f7ce8a2f1664678568a464af81"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-85f25624f5c3/fa94e72d4348/preview.png",
      "size": 65727,
      "sha1": "a68186f501678bdbd787ec7e805e21dc43979a65"
    },
    "localPreview": "/packages/avatars/previews/local-85f25624f5c3.jpg"
  },
  {
    "id": "local-39b7c0bcd154",
    "name": "Eldridge (New Year's Handholding)",
    "family": "碧蓝航线",
    "version": "5c3206bfb2a7",
    "model": {
      "cloudPath": "ning/avatars/v1/local-39b7c0bcd154/5c3206bfb2a7/model.moc3",
      "size": 533120,
      "sha1": "ba0665158100dc80204666b79c3b9d659f809dc2"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-39b7c0bcd154/5c3206bfb2a7/texture-0.png",
        "size": 4523470,
        "sha1": "9b61bdc3113efb7998fc69685cbef4b1a39d513f"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-39b7c0bcd154/5c3206bfb2a7/preview.png",
      "size": 82132,
      "sha1": "ab014e819d91e81c118b7a9871e21d96097b150a"
    },
    "localPreview": "/packages/avatars/previews/local-39b7c0bcd154.jpg"
  },
  {
    "id": "local-65a9b84ee619",
    "name": "Eldridge",
    "family": "碧蓝航线",
    "version": "512eceff8ce4",
    "model": {
      "cloudPath": "ning/avatars/v1/local-65a9b84ee619/512eceff8ce4/model.moc3",
      "size": 1972288,
      "sha1": "0c295c897a94929eeef53e75255ad6c6e104e1c8"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-65a9b84ee619/512eceff8ce4/texture-0.png",
        "size": 4026326,
        "sha1": "d0fe71273c2c4673fb50d8db05afc2345d18aa5b"
      },
      {
        "cloudPath": "ning/avatars/v1/local-65a9b84ee619/512eceff8ce4/texture-1.png",
        "size": 611635,
        "sha1": "3b4132d2bd8c3b9c0419a62ac27c32168c70ce04"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-65a9b84ee619/512eceff8ce4/preview.png",
      "size": 42675,
      "sha1": "4673c76c5c487274157a1d0a1103bb44a2d1c76e"
    },
    "localPreview": "/packages/avatars/previews/local-65a9b84ee619.jpg"
  },
  {
    "id": "local-a52bbb186d1c",
    "name": "Emile Bertin (Côte d'Azur)",
    "family": "碧蓝航线",
    "version": "c4c7beec4735",
    "model": {
      "cloudPath": "ning/avatars/v1/local-a52bbb186d1c/c4c7beec4735/model.moc3",
      "size": 600832,
      "sha1": "e08f6ab513d9e4270f248c9f87e9783aee3ebbc5"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-a52bbb186d1c/c4c7beec4735/texture-0.png",
        "size": 1268744,
        "sha1": "e896a768f6bb0f2771f89cd81c4bf9d3688c5ff0"
      },
      {
        "cloudPath": "ning/avatars/v1/local-a52bbb186d1c/c4c7beec4735/texture-1.png",
        "size": 1162328,
        "sha1": "ed933dc4221628af490ead14eda9200a3ef2ce72"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-a52bbb186d1c/c4c7beec4735/preview.png",
      "size": 71505,
      "sha1": "1da64036877fb2354514c329688cd60dddca4dcf"
    },
    "localPreview": "/packages/avatars/previews/local-a52bbb186d1c.jpg"
  },
  {
    "id": "local-ed37f140f327",
    "name": "Centaur (Undine of the Beach)",
    "family": "碧蓝航线",
    "version": "14d2a419ce8a",
    "model": {
      "cloudPath": "ning/avatars/v1/local-ed37f140f327/14d2a419ce8a/model.moc3",
      "size": 751104,
      "sha1": "37ff4ad5b58d3111570ee24f435d09bba59fabc4"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-ed37f140f327/14d2a419ce8a/texture-0.png",
        "size": 986299,
        "sha1": "8b79351f559e027b345af6be00bbc4606d42fb86"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-ed37f140f327/14d2a419ce8a/preview.png",
      "size": 45343,
      "sha1": "91e11a9e9576f8ff3a53dd261ba3693462452fab"
    },
    "localPreview": "/packages/avatars/previews/local-ed37f140f327.jpg"
  },
  {
    "id": "local-9576dfc57483",
    "name": "Belfast (Iridescent Rose)",
    "family": "碧蓝航线",
    "version": "ecbd4ec279e0",
    "model": {
      "cloudPath": "ning/avatars/v1/local-9576dfc57483/ecbd4ec279e0/model.moc3",
      "size": 1177216,
      "sha1": "936add0c85a17dd430b24ea64b729d12e090c959"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-9576dfc57483/ecbd4ec279e0/texture-0.png",
        "size": 4438125,
        "sha1": "1c97b63f0800b9a58e9e111399506f9d271ccf86"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-9576dfc57483/ecbd4ec279e0/preview.png",
      "size": 56099,
      "sha1": "0b94977c22d251e687c1c1e49d30f600cdd48bf4"
    },
    "localPreview": "/packages/avatars/previews/local-9576dfc57483.jpg"
  },
  {
    "id": "local-6de22b43ba65",
    "name": "Javelin",
    "family": "碧蓝航线",
    "version": "7fe379a05cc1",
    "model": {
      "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/model.moc3",
      "size": 564480,
      "sha1": "401526983679074bfb474c7420ccec1201c447fe"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-0.png",
        "size": 137111,
        "sha1": "d6af5a8317b04ce17160d98a18e4c2c6eb1fc8bb"
      },
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-1.png",
        "size": 185162,
        "sha1": "4cfc396a57321b8859ff0bced592a90f645c059c"
      },
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-2.png",
        "size": 153187,
        "sha1": "b6d7afb0f79ee7089f7e6684e128f64dae662b4d"
      },
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-3.png",
        "size": 517625,
        "sha1": "1f8284c93ed034a29293f462564356c425b3bf2d"
      },
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-4.png",
        "size": 616836,
        "sha1": "fcc068a37e3c995cd723aee4db9e76635caab155"
      },
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-5.png",
        "size": 136931,
        "sha1": "ef95be1ed0a9f45604e9163bf0562fc9a4cda0df"
      },
      {
        "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/texture-6.png",
        "size": 140345,
        "sha1": "db86ae14360d99b4aebd839168d45b62ae0c0e5e"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-6de22b43ba65/7fe379a05cc1/preview.png",
      "size": 49056,
      "sha1": "21b2784c372ce074b98808835959f3b84336f805"
    },
    "localPreview": "/packages/avatars/previews/local-6de22b43ba65.jpg"
  },
  {
    "id": "local-6664508bf153",
    "name": "Javelin (Beach Picnic!)",
    "family": "碧蓝航线",
    "version": "f1976fcb2e2f",
    "model": {
      "cloudPath": "ning/avatars/v1/local-6664508bf153/f1976fcb2e2f/model.moc3",
      "size": 607104,
      "sha1": "bd60ed23adda6472f1746fea7d88a9ef592122ae"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-6664508bf153/f1976fcb2e2f/texture-0.png",
        "size": 1195933,
        "sha1": "55b98acb3e8a64a4deb3f920952a9b1d1c34c0d5"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-6664508bf153/f1976fcb2e2f/preview.png",
      "size": 67693,
      "sha1": "eb9d3305b9406c7da71f3d93138b7e116aa9b6d7"
    },
    "localPreview": "/packages/avatars/previews/local-6664508bf153.jpg"
  },
  {
    "id": "local-0167e0df5d0c",
    "name": "Bismarck (Majesty of the Ironblood) · 备用配置",
    "family": "碧蓝航线",
    "version": "4c3f39708307",
    "model": {
      "cloudPath": "ning/avatars/v1/local-0167e0df5d0c/4c3f39708307/model.moc3",
      "size": 773632,
      "sha1": "ce211050b2f7c6a589d349f8dd2578d73adc0b68"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-0167e0df5d0c/4c3f39708307/texture-0.png",
        "size": 1172435,
        "sha1": "5f31e35d457b5ef365924e97fcf4b1a716bc1d72"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-0167e0df5d0c/4c3f39708307/preview.png",
      "size": 64764,
      "sha1": "33c4f04802cd12192b7722a2337ad088f38e8f20"
    },
    "localPreview": "/packages/avatars/previews/local-0167e0df5d0c.jpg"
  },
  {
    "id": "local-73b9a40dbffb",
    "name": "Bismarck (Majesty of the Ironblood)",
    "family": "碧蓝航线",
    "version": "561518dccae4",
    "model": {
      "cloudPath": "ning/avatars/v1/local-73b9a40dbffb/561518dccae4/model.moc3",
      "size": 830656,
      "sha1": "cfe2b1becad259dce23b91509ac359e9db1fb072"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-73b9a40dbffb/561518dccae4/texture-0.png",
        "size": 1172435,
        "sha1": "5f31e35d457b5ef365924e97fcf4b1a716bc1d72"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-73b9a40dbffb/561518dccae4/preview.png",
      "size": 57543,
      "sha1": "e45a2aaf36ccefd83082216caf164f102cb241ab"
    },
    "localPreview": "/packages/avatars/previews/local-73b9a40dbffb.jpg"
  },
  {
    "id": "local-c4a3396d23ff",
    "name": "Fubuki (Music Pixy)",
    "family": "碧蓝航线",
    "version": "9b615a674a5d",
    "model": {
      "cloudPath": "ning/avatars/v1/local-c4a3396d23ff/9b615a674a5d/model.moc3",
      "size": 732288,
      "sha1": "ee6bb28003bf4f3fbce5d131fc1ac82afc630873"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-c4a3396d23ff/9b615a674a5d/texture-0.png",
        "size": 2524610,
        "sha1": "c1236ecc0c36e2b438457628caed3aea5a482758"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-c4a3396d23ff/9b615a674a5d/preview.png",
      "size": 56291,
      "sha1": "2b29c0a551f9fb79590ff7db8e18d8b9d22884a7"
    },
    "localPreview": "/packages/avatars/previews/local-c4a3396d23ff.jpg"
  },
  {
    "id": "local-e42d6d8467a8",
    "name": "Taihou (Forbidden Feast)",
    "family": "碧蓝航线",
    "version": "5796e1b41e13",
    "model": {
      "cloudPath": "ning/avatars/v1/local-e42d6d8467a8/5796e1b41e13/model.moc3",
      "size": 986176,
      "sha1": "dbb9237df62883d131c0bf0831308f84679ffa34"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-e42d6d8467a8/5796e1b41e13/texture-0.png",
        "size": 2817735,
        "sha1": "58cb84bd2416ccaf2da3052b9f40fb52f9e688dd"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-e42d6d8467a8/5796e1b41e13/preview.png",
      "size": 58136,
      "sha1": "34b740c00f7723131e61fac7b1c5664bc053d952"
    },
    "localPreview": "/packages/avatars/previews/local-e42d6d8467a8.jpg"
  },
  {
    "id": "local-b7c43e4a16f4",
    "name": "Deutschland (Service Time?!)",
    "family": "碧蓝航线",
    "version": "62246ea1e207",
    "model": {
      "cloudPath": "ning/avatars/v1/local-b7c43e4a16f4/62246ea1e207/model.moc3",
      "size": 621120,
      "sha1": "3dff007acdb411c3eb482f1f9bede136e11a72e6"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-b7c43e4a16f4/62246ea1e207/texture-0.png",
        "size": 966807,
        "sha1": "bc89e0304ff97f853b230f18cb108cd09cde9df9"
      },
      {
        "cloudPath": "ning/avatars/v1/local-b7c43e4a16f4/62246ea1e207/texture-1.png",
        "size": 1045639,
        "sha1": "ac9bfdc8784d6e8dbfdcda571f2f23f43b5b02ae"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-b7c43e4a16f4/62246ea1e207/preview.png",
      "size": 69210,
      "sha1": "9315c6b2bc84576437d5e041967a90805cedd7e2"
    },
    "localPreview": "/packages/avatars/previews/local-b7c43e4a16f4.jpg"
  },
  {
    "id": "local-e41a0c815c71",
    "name": "Unicorn (Amusement Park Date)",
    "family": "碧蓝航线",
    "version": "296eec942d5a",
    "model": {
      "cloudPath": "ning/avatars/v1/local-e41a0c815c71/296eec942d5a/model.moc3",
      "size": 785984,
      "sha1": "2f2608b07ec1dfb01037ffcbca9b285a465e77d3"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-e41a0c815c71/296eec942d5a/texture-0.png",
        "size": 1169633,
        "sha1": "0b55143559729e195154d44b6df8a724e7afa7c7"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-e41a0c815c71/296eec942d5a/preview.png",
      "size": 55235,
      "sha1": "608e1db6a9337662640006d82630f0b10bdae56a"
    },
    "localPreview": "/packages/avatars/previews/local-e41a0c815c71.jpg"
  },
  {
    "id": "local-6d946c3fe9b2",
    "name": "Dunkerque (Summer Sucré)",
    "family": "碧蓝航线",
    "version": "3ed42e6152ef",
    "model": {
      "cloudPath": "ning/avatars/v1/local-6d946c3fe9b2/3ed42e6152ef/model.moc3",
      "size": 783168,
      "sha1": "5237305a4347924ac392ea21fdefbd6aaf30d27e"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-6d946c3fe9b2/3ed42e6152ef/texture-0.png",
        "size": 1237103,
        "sha1": "50124060ed694eb1aaced0aefb80681f90e93a7f"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-6d946c3fe9b2/3ed42e6152ef/preview.png",
      "size": 114235,
      "sha1": "c2ba8ff606c974ddb595af3a12450c14b4100ac6"
    },
    "localPreview": "/packages/avatars/previews/local-6d946c3fe9b2.jpg"
  },
  {
    "id": "local-873b66308316",
    "name": "Gneisenau",
    "family": "碧蓝航线",
    "version": "ccefa4d3a517",
    "model": {
      "cloudPath": "ning/avatars/v1/local-873b66308316/ccefa4d3a517/model.moc3",
      "size": 753408,
      "sha1": "d629f0136c012bd8486ecd17c62ddbfa3384f366"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-873b66308316/ccefa4d3a517/texture-0.png",
        "size": 3041638,
        "sha1": "943ea6c93283a1ec08c0747d7be6d1c205043b6d"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-873b66308316/ccefa4d3a517/preview.png",
      "size": 68830,
      "sha1": "bb121f11b9fea7b24cf5d6d847516c0b36620c93"
    },
    "localPreview": "/packages/avatars/previews/local-873b66308316.jpg"
  },
  {
    "id": "local-c44404b509f7",
    "name": "Black Prince",
    "family": "碧蓝航线",
    "version": "7532477706b0",
    "model": {
      "cloudPath": "ning/avatars/v1/local-c44404b509f7/7532477706b0/model.moc3",
      "size": 860800,
      "sha1": "d18793f921f7f10580fe4a24c1ca016699bcfb8d"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-c44404b509f7/7532477706b0/texture-0.png",
        "size": 5591199,
        "sha1": "914f0e681d08de2b93f07814ad8b5c215bd0f998"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-c44404b509f7/7532477706b0/preview.png",
      "size": 69554,
      "sha1": "9408af40fe86dfbd70bee7dc88386dc0ff3b8c9b"
    },
    "localPreview": "/packages/avatars/previews/local-c44404b509f7.jpg"
  },
  {
    "id": "local-08e25ef9dbeb",
    "name": "Ark Royal (Banquet Guardian)",
    "family": "碧蓝航线",
    "version": "289f465333e3",
    "model": {
      "cloudPath": "ning/avatars/v1/local-08e25ef9dbeb/289f465333e3/model.moc3",
      "size": 1385344,
      "sha1": "0b07a37c8a259a4e10a3b0a3009a527b61fc3588"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-08e25ef9dbeb/289f465333e3/texture-0.png",
        "size": 3667752,
        "sha1": "08e69a0cf0e036111934a3ca0934fc5c0d3832e6"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-08e25ef9dbeb/289f465333e3/preview.png",
      "size": 95356,
      "sha1": "1ff38a036949a622598b02f1e6ae47d1d47e48c6"
    },
    "localPreview": "/packages/avatars/previews/local-08e25ef9dbeb.jpg"
  },
  {
    "id": "local-477171b17dd0",
    "name": "Honolulu (Summer Accident?!)",
    "family": "碧蓝航线",
    "version": "d4bd480e8056",
    "model": {
      "cloudPath": "ning/avatars/v1/local-477171b17dd0/d4bd480e8056/model.moc3",
      "size": 918976,
      "sha1": "3239be65f9cfc36df10dfc51f934199af6203c20"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-477171b17dd0/d4bd480e8056/texture-0.png",
        "size": 1166239,
        "sha1": "236e0b96ef063a5674911be9f67762df7e721eaf"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-477171b17dd0/d4bd480e8056/preview.png",
      "size": 56132,
      "sha1": "3a40308ddffb1584524a268ca5cc632a0dbca191"
    },
    "localPreview": "/packages/avatars/previews/local-477171b17dd0.jpg"
  },
  {
    "id": "local-e2f2fb017aef",
    "name": "Honolulu",
    "family": "碧蓝航线",
    "version": "2e63601739a8",
    "model": {
      "cloudPath": "ning/avatars/v1/local-e2f2fb017aef/2e63601739a8/model.moc3",
      "size": 1981504,
      "sha1": "6f7fb71d67fa380f1c5bd85aabcb9c2d8989eaee"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-e2f2fb017aef/2e63601739a8/texture-0.png",
        "size": 3971550,
        "sha1": "3e7818cc2158aec3d1a0e507912da92bcb5e0ab9"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-e2f2fb017aef/2e63601739a8/preview.png",
      "size": 113245,
      "sha1": "73770755f345c9ed7365abd5b7748bb0389f8164"
    },
    "localPreview": "/packages/avatars/previews/local-e2f2fb017aef.jpg"
  },
  {
    "id": "local-0e6f0b5dd556",
    "name": "Cleveland (Gentry Knight)",
    "family": "碧蓝航线",
    "version": "272c34594969",
    "model": {
      "cloudPath": "ning/avatars/v1/local-0e6f0b5dd556/272c34594969/model.moc3",
      "size": 1525184,
      "sha1": "e8676d12d658f634e10170872ac543a7e08a8f4e"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-0e6f0b5dd556/272c34594969/texture-0.png",
        "size": 3390968,
        "sha1": "3ac2839398663872a7c23ba78395578a8e31c123"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-0e6f0b5dd556/272c34594969/preview.png",
      "size": 66194,
      "sha1": "0bb923883f0b661a014c980a4a7e3f6dc747737f"
    },
    "localPreview": "/packages/avatars/previews/local-0e6f0b5dd556.jpg"
  },
  {
    "id": "local-a60b422bcd02",
    "name": "Laffey",
    "family": "碧蓝航线",
    "version": "e1f6be0db166",
    "model": {
      "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/model.moc3",
      "size": 651392,
      "sha1": "87ad1143491c6653d36f3e4a4f8af47657ed5ff5"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/texture-0.png",
        "size": 131811,
        "sha1": "c2d9d39f145273d89908b0d796ab4a08c69bec9f"
      },
      {
        "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/texture-1.png",
        "size": 167255,
        "sha1": "b8a132426dc1b7fc88151f251d2a8a8633c05396"
      },
      {
        "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/texture-2.png",
        "size": 93916,
        "sha1": "3ca5e743df60412cbbfdb8506da7a9d7fe76665c"
      },
      {
        "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/texture-3.png",
        "size": 1577341,
        "sha1": "2d6a7bd64d2a819ffc7bc5ef9d86cfaba9ce708f"
      },
      {
        "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/texture-4.png",
        "size": 138706,
        "sha1": "1c79ae6c9ebd625488fb82b1397035b44a933fab"
      },
      {
        "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/texture-5.png",
        "size": 553687,
        "sha1": "3e5725d485ac10b0eef38c54f8922c43d91fee0f"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-a60b422bcd02/e1f6be0db166/preview.png",
      "size": 65888,
      "sha1": "4e8eb4cba0dc49a798abadfa4bd42c9558c6bdb9"
    },
    "localPreview": "/packages/avatars/previews/local-a60b422bcd02.jpg"
  },
  {
    "id": "local-aab083d2d00a",
    "name": "Laffey (New Year Rabbit)",
    "family": "碧蓝航线",
    "version": "fd8ed64f0287",
    "model": {
      "cloudPath": "ning/avatars/v1/local-aab083d2d00a/fd8ed64f0287/model.moc3",
      "size": 1515776,
      "sha1": "a7350706a6a451bc5fca93ca913e244bd948708a"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-aab083d2d00a/fd8ed64f0287/texture-0.png",
        "size": 1398226,
        "sha1": "1e8e889cf15c19c4deec1f36b8f140e22917000c"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-aab083d2d00a/fd8ed64f0287/preview.png",
      "size": 91191,
      "sha1": "4b3461ef73e65fbf74d2686f00d34e640b2f415d"
    },
    "localPreview": "/packages/avatars/previews/local-aab083d2d00a.jpg"
  },
  {
    "id": "local-29ba1afcca6a",
    "name": "Ayanami",
    "family": "碧蓝航线",
    "version": "2427cfd1358f",
    "model": {
      "cloudPath": "ning/avatars/v1/local-29ba1afcca6a/2427cfd1358f/model.moc3",
      "size": 877504,
      "sha1": "5f6c24a86ce58fe7b969bb4158ef6a24a5819aa3"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-29ba1afcca6a/2427cfd1358f/texture-0.png",
        "size": 103642,
        "sha1": "9fd45e085db3f86927eca39dd9848aa12d1e05f8"
      },
      {
        "cloudPath": "ning/avatars/v1/local-29ba1afcca6a/2427cfd1358f/texture-1.png",
        "size": 112473,
        "sha1": "889efb422be225c777976c2837b972859c807dd7"
      },
      {
        "cloudPath": "ning/avatars/v1/local-29ba1afcca6a/2427cfd1358f/texture-2.png",
        "size": 227699,
        "sha1": "49d74091beb759e2b5db9036fd648f0b34f53cb1"
      },
      {
        "cloudPath": "ning/avatars/v1/local-29ba1afcca6a/2427cfd1358f/texture-3.png",
        "size": 636193,
        "sha1": "f40056c85cb00815a6cb02c5d61ec7d84b941e67"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-29ba1afcca6a/2427cfd1358f/preview.png",
      "size": 51725,
      "sha1": "3d469233f9deb409948d6ff2d63fc11c4b9e4f79"
    },
    "localPreview": "/packages/avatars/previews/local-29ba1afcca6a.jpg"
  },
  {
    "id": "local-6227504486bb",
    "name": "Akashi",
    "family": "碧蓝航线",
    "version": "b5eff613a281",
    "model": {
      "cloudPath": "ning/avatars/v1/local-6227504486bb/b5eff613a281/model.moc3",
      "size": 465728,
      "sha1": "5ecdeda11c6962f9319ef2df4eeea08c0f16db15"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-6227504486bb/b5eff613a281/texture-0.png",
        "size": 840334,
        "sha1": "998106bde5df62435db1c07c76912ec386aa12a8"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-6227504486bb/b5eff613a281/preview.png",
      "size": 82327,
      "sha1": "d0d5f689fd7ff2264b176736c723f748fde8b673"
    },
    "localPreview": "/packages/avatars/previews/local-6227504486bb.jpg"
  },
  {
    "id": "local-34b8be351ff4",
    "name": "Ning Hai",
    "family": "碧蓝航线",
    "version": "31ddcf89b049",
    "model": {
      "cloudPath": "ning/avatars/v1/local-34b8be351ff4/31ddcf89b049/model.moc3",
      "size": 1329152,
      "sha1": "0f1ca8f41cba00b00880330634aa5ba6cea27eb3"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-34b8be351ff4/31ddcf89b049/texture-0.png",
        "size": 3076181,
        "sha1": "fe3b3406a9fe2adf2418d72ab9d0a2df3eb9a9ce"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-34b8be351ff4/31ddcf89b049/preview.png",
      "size": 34329,
      "sha1": "6cfb419450824281fbb1465b3ee7c8e2c8c0f3da"
    },
    "localPreview": "/packages/avatars/previews/local-34b8be351ff4.jpg"
  },
  {
    "id": "local-7342b5d7c248",
    "name": "Ping Hai",
    "family": "碧蓝航线",
    "version": "99ec06ca1169",
    "model": {
      "cloudPath": "ning/avatars/v1/local-7342b5d7c248/99ec06ca1169/model.moc3",
      "size": 1183616,
      "sha1": "627f6dc822aabed148309e7505bc9fd5749dfabd"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-7342b5d7c248/99ec06ca1169/texture-0.png",
        "size": 3343906,
        "sha1": "674b16edfe30317cfb73a5a754ec70b351ff6dee"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-7342b5d7c248/99ec06ca1169/preview.png",
      "size": 35828,
      "sha1": "2655065ca3558081196723ddc9f4320fc6293be8"
    },
    "localPreview": "/packages/avatars/previews/local-7342b5d7c248.jpg"
  },
  {
    "id": "local-966ad8a3afd8",
    "name": "Graf Zeppelin (Beachside Urd)",
    "family": "碧蓝航线",
    "version": "7f56e2c57cb1",
    "model": {
      "cloudPath": "ning/avatars/v1/local-966ad8a3afd8/7f56e2c57cb1/model.moc3",
      "size": 1039232,
      "sha1": "654af759cb8a6a91da853d0762489516f69be7a4"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-966ad8a3afd8/7f56e2c57cb1/texture-0.png",
        "size": 2750640,
        "sha1": "8697d0d3502d60af2279dbe32619dd029288c792"
      },
      {
        "cloudPath": "ning/avatars/v1/local-966ad8a3afd8/7f56e2c57cb1/texture-1.png",
        "size": 1085109,
        "sha1": "2db9eff4b0de44eeb9b30288ced388968e7f3c62"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-966ad8a3afd8/7f56e2c57cb1/preview.png",
      "size": 80862,
      "sha1": "075bceffa744becd8673d9fcd08c451d93ba4612"
    },
    "localPreview": "/packages/avatars/previews/local-966ad8a3afd8.jpg"
  },
  {
    "id": "local-5a9f85678090",
    "name": "St. Louis (Splendor of Spring)",
    "family": "碧蓝航线",
    "version": "69ee6bd910dc",
    "model": {
      "cloudPath": "ning/avatars/v1/local-5a9f85678090/69ee6bd910dc/model.moc3",
      "size": 451712,
      "sha1": "acc6a577c0cc48e195b1ab82cea5304d265fe302"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-5a9f85678090/69ee6bd910dc/texture-0.png",
        "size": 1052249,
        "sha1": "5aa1666521d7ca903ef9497063b1fff71025e91e"
      },
      {
        "cloudPath": "ning/avatars/v1/local-5a9f85678090/69ee6bd910dc/texture-1.png",
        "size": 1327461,
        "sha1": "69563be597efa8493d11ef8133886ab0306ac53f"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-5a9f85678090/69ee6bd910dc/preview.png",
      "size": 59893,
      "sha1": "d6de65e5672881b8034a3d015fd521c34bf2862e"
    },
    "localPreview": "/packages/avatars/previews/local-5a9f85678090.jpg"
  },
  {
    "id": "local-7994dec357ce",
    "name": "Admiral Graf Spee",
    "family": "碧蓝航线",
    "version": "437a2d3449cd",
    "model": {
      "cloudPath": "ning/avatars/v1/local-7994dec357ce/437a2d3449cd/model.moc3",
      "size": 655936,
      "sha1": "60013d03346eebb56b7366ceb3112bf352d97a1c"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-7994dec357ce/437a2d3449cd/texture-0.png",
        "size": 3132711,
        "sha1": "1a4161a3598c6e2d3c9150d6ae527d1274605dea"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-7994dec357ce/437a2d3449cd/preview.png",
      "size": 99389,
      "sha1": "6f251f3214923efa3c665686eebac408fed0d837"
    },
    "localPreview": "/packages/avatars/previews/local-7994dec357ce.jpg"
  },
  {
    "id": "local-0d72a7046dfc",
    "name": "Tai Yuan (Clamorous Tortoise)",
    "family": "碧蓝航线",
    "version": "ebc8b1ce8f51",
    "model": {
      "cloudPath": "ning/avatars/v1/local-0d72a7046dfc/ebc8b1ce8f51/model.moc3",
      "size": 542848,
      "sha1": "baa9b1ee1d3c2dd3bae1018b43389ce4b23f215e"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-0d72a7046dfc/ebc8b1ce8f51/texture-0.png",
        "size": 982136,
        "sha1": "6760cd019be2b95ffb139b762f8260aebcaf2125"
      },
      {
        "cloudPath": "ning/avatars/v1/local-0d72a7046dfc/ebc8b1ce8f51/texture-1.png",
        "size": 789899,
        "sha1": "0de88fc225317b1dd38324aa9e3f9bc15ad44c08"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-0d72a7046dfc/ebc8b1ce8f51/preview.png",
      "size": 73569,
      "sha1": "e845e35188b3a823b8674614d3f91f6052166987"
    },
    "localPreview": "/packages/avatars/previews/local-0d72a7046dfc.jpg"
  },
  {
    "id": "local-3ddd849e3a8a",
    "name": "Sirius (Midsummer Seirios)",
    "family": "碧蓝航线",
    "version": "c08e6767d914",
    "model": {
      "cloudPath": "ning/avatars/v1/local-3ddd849e3a8a/c08e6767d914/model.moc3",
      "size": 459456,
      "sha1": "064f2ef277b4d1bef217e4941a9e2cf218c5130f"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-3ddd849e3a8a/c08e6767d914/texture-0.png",
        "size": 2558971,
        "sha1": "a5c7b88a173cbfd5b19cc72c277e692a0babbd69"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-3ddd849e3a8a/c08e6767d914/preview.png",
      "size": 74505,
      "sha1": "ecfc838d4fcdd6a5a86d77192baba24e226cdd1d"
    },
    "localPreview": "/packages/avatars/previews/local-3ddd849e3a8a.jpg"
  },
  {
    "id": "local-534e67321374",
    "name": "Tirpitz (Snow-melting Summer)",
    "family": "碧蓝航线",
    "version": "39a3e9075d57",
    "model": {
      "cloudPath": "ning/avatars/v1/local-534e67321374/39a3e9075d57/model.moc3",
      "size": 749376,
      "sha1": "dfc07502ca75df0e7c364f69175fcd399cb49934"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-534e67321374/39a3e9075d57/texture-0.png",
        "size": 1132344,
        "sha1": "2af38ceedd74b22b43f39dcdf0a0cd8f614487f6"
      },
      {
        "cloudPath": "ning/avatars/v1/local-534e67321374/39a3e9075d57/texture-1.png",
        "size": 1308550,
        "sha1": "58d279e73daebc4c8795bd425ef0f8af680c5b03"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-534e67321374/39a3e9075d57/preview.png",
      "size": 74652,
      "sha1": "57622141cc9c7d1dc93f21635737153d86f6ac9f"
    },
    "localPreview": "/packages/avatars/previews/local-534e67321374.jpg"
  },
  {
    "id": "local-45708538a547",
    "name": "Shōkaku",
    "family": "碧蓝航线",
    "version": "53b02434f144",
    "model": {
      "cloudPath": "ning/avatars/v1/local-45708538a547/53b02434f144/model.moc3",
      "size": 1172416,
      "sha1": "13c05f796b81e0c8e222b0d63832952df5fe00b0"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-45708538a547/53b02434f144/texture-0.png",
        "size": 4064892,
        "sha1": "46d11fd9fc92690a2542d8207cffe9958e2b492e"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-45708538a547/53b02434f144/preview.png",
      "size": 46809,
      "sha1": "ba67ca03b8360822fb4ac4a3ae8c0d87d93c6f5e"
    },
    "localPreview": "/packages/avatars/previews/local-45708538a547.jpg"
  },
  {
    "id": "local-b7e047abf804",
    "name": "Vampire",
    "family": "碧蓝航线",
    "version": "b02442b64e92",
    "model": {
      "cloudPath": "ning/avatars/v1/local-b7e047abf804/b02442b64e92/model.moc3",
      "size": 529216,
      "sha1": "9375bc0915eb549fac6cf85d1f45e7f8cf966bc9"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-b7e047abf804/b02442b64e92/texture-0.png",
        "size": 4146511,
        "sha1": "fef5bebc6b30df9993c3db6ac3b0d46b06720604"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-b7e047abf804/b02442b64e92/preview.png",
      "size": 85357,
      "sha1": "f304044faf0249b9f3634fb35b3b32b3c45f7f6e"
    },
    "localPreview": "/packages/avatars/previews/local-b7e047abf804.jpg"
  },
  {
    "id": "local-84c65202f41f",
    "name": "Yukikaze",
    "family": "碧蓝航线",
    "version": "c0d2974a8a67",
    "model": {
      "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/model.moc3",
      "size": 588736,
      "sha1": "d8702629d654e13cf7fd68d2c9945224e69f74e4"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/texture-0.png",
        "size": 155672,
        "sha1": "e38302bf71adee5b2e1791a2d97fb08ac0e06cf2"
      },
      {
        "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/texture-1.png",
        "size": 179620,
        "sha1": "d4d8d92cbc980e7a2cdef5916f70e0a370bbd456"
      },
      {
        "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/texture-2.png",
        "size": 144296,
        "sha1": "498c70de246db7c39f036267f3b810b974c44f7e"
      },
      {
        "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/texture-3.png",
        "size": 552157,
        "sha1": "d507608cd674a1941ce4cd540930d9aafdb09411"
      },
      {
        "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/texture-4.png",
        "size": 657470,
        "sha1": "7e6d444650c268c95a64e722c9d78d7a88ef7f80"
      },
      {
        "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/texture-5.png",
        "size": 159240,
        "sha1": "dcfb4a279194ec4bbad1f5b79d32ff8a3cf63817"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-84c65202f41f/c0d2974a8a67/preview.png",
      "size": 80100,
      "sha1": "e67280c2e3ea0b6a5c4ab9809b6fc46f5ae0e776"
    },
    "localPreview": "/packages/avatars/previews/local-84c65202f41f.jpg"
  },
  {
    "id": "local-59b4b716ec60",
    "name": "Ibuki (Wish of a Snow Goddess)",
    "family": "碧蓝航线",
    "version": "8757b6874a96",
    "model": {
      "cloudPath": "ning/avatars/v1/local-59b4b716ec60/8757b6874a96/model.moc3",
      "size": 1410432,
      "sha1": "a1c6f25e4b476535eae8ad7408af5db4d751f15e"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-59b4b716ec60/8757b6874a96/texture-0.png",
        "size": 4440483,
        "sha1": "91478da42783a79b68efa9e51f6c2a49f36978f5"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-59b4b716ec60/8757b6874a96/preview.png",
      "size": 78594,
      "sha1": "cfb23456c31945f85729bec5f7f3fd8a4a13939b"
    },
    "localPreview": "/packages/avatars/previews/local-59b4b716ec60.jpg"
  },
  {
    "id": "local-fa1e2c564c99",
    "name": "Z23",
    "family": "碧蓝航线",
    "version": "0a7822103c32",
    "model": {
      "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/model.moc3",
      "size": 448896,
      "sha1": "3ef4841bebb48da310a54b7c5e8b54c7162cd324"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/texture-0.png",
        "size": 125794,
        "sha1": "abe4aec043d1fc82da506926a66670e2b329c4ae"
      },
      {
        "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/texture-1.png",
        "size": 185650,
        "sha1": "4c8f6302f58c884ba4d579887d4993d8e87d89d1"
      },
      {
        "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/texture-2.png",
        "size": 134367,
        "sha1": "0db3e90e2528567b995cbdc6c8cf65423078a2fb"
      },
      {
        "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/texture-3.png",
        "size": 232207,
        "sha1": "b4eab4de31c042ccd0a9793ba5752b00a2d8599a"
      },
      {
        "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/texture-4.png",
        "size": 538322,
        "sha1": "6037e6aec93106c35cffab7aed53384d87aadcdd"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-fa1e2c564c99/0a7822103c32/preview.png",
      "size": 45123,
      "sha1": "b2191292005eeee914d998d3e0c39cfa5d449f36"
    },
    "localPreview": "/packages/avatars/previews/local-fa1e2c564c99.jpg"
  },
  {
    "id": "local-23d4a69218d5",
    "name": "Z46 (First Summer)",
    "family": "碧蓝航线",
    "version": "ea1b5da16583",
    "model": {
      "cloudPath": "ning/avatars/v1/local-23d4a69218d5/ea1b5da16583/model.moc3",
      "size": 681408,
      "sha1": "9a84b02beaf137312c3eda0e8446a7a571740ce5"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/local-23d4a69218d5/ea1b5da16583/texture-0.png",
        "size": 2789318,
        "sha1": "fe168e8e9ab99db417e3c07e8eaeb24ec41e9e2a"
      },
      {
        "cloudPath": "ning/avatars/v1/local-23d4a69218d5/ea1b5da16583/texture-1.png",
        "size": 1862078,
        "sha1": "09ec7827228f6df101785b95c74373837b50862a"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/local-23d4a69218d5/ea1b5da16583/preview.png",
      "size": 92124,
      "sha1": "6d671a1ed41d5d537eb0c43a46dcc9f65dd2893d"
    },
    "localPreview": "/packages/avatars/previews/local-23d4a69218d5.jpg"
  },
  {
    "id": "l2d-models-615c42add339-4e5439bce8f7",
    "name": "abeikelongbi_3",
    "family": "碧蓝航线",
    "version": "f89fde60bb75",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-4e5439bce8f7/f89fde60bb75/model.moc3",
      "size": 2606912,
      "sha1": "04b4efb1c645275ad4fbda56cefea0a2da055668"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-4e5439bce8f7/f89fde60bb75/texture-0.png",
        "size": 4847308,
        "sha1": "645f0ae4383c44ce7a06d40f1ddf9c9c4bb88cc7"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-4e5439bce8f7/f89fde60bb75/preview.png",
      "size": 104356,
      "sha1": "6ec6d4d95c42f208a5aeca59419320ad99ec9a12"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-4e5439bce8f7.jpg"
  },
  {
    "id": "l2d-models-615c42add339-68ab616026f4",
    "name": "Haru",
    "family": "碧蓝航线",
    "version": "68555660156a",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-68ab616026f4/68555660156a/model.moc3",
      "size": 384704,
      "sha1": "163a7543e1e4cfa54431885ee4ed76c2f51706a1"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-68ab616026f4/68555660156a/texture-0.png",
        "size": 1526786,
        "sha1": "6ec7b7247d2dc8d843e0b2535f325e81bbf3a55d"
      },
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-68ab616026f4/68555660156a/texture-1.png",
        "size": 1188664,
        "sha1": "85bbf44931bd6ee90b6b35d361e54ecd10a4cb1d"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-68ab616026f4/68555660156a/preview.png",
      "size": 25374,
      "sha1": "cc9b3e995aa040d57244a416af8ed0f035515280"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-68ab616026f4.jpg"
  },
  {
    "id": "l2d-models-615c42add339-bc879545841d",
    "name": "Hiyori",
    "family": "碧蓝航线",
    "version": "a38d5aabb9e3",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-bc879545841d/a38d5aabb9e3/model.moc3",
      "size": 443648,
      "sha1": "ed380f02dc74623bd1b78a3d3af2bdf81ada128b"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-bc879545841d/a38d5aabb9e3/texture-0.png",
        "size": 1814312,
        "sha1": "3dc99be2fad743fb407b7861dbb73deb61eee420"
      },
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-bc879545841d/a38d5aabb9e3/texture-1.png",
        "size": 2504416,
        "sha1": "4208351b9d017f427effe73533bcd9e0bf261cf7"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-bc879545841d/a38d5aabb9e3/preview.png",
      "size": 34001,
      "sha1": "784aa615124ce6cd26c1b8a5640d5f46fa3fb4a4"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-bc879545841d.jpg"
  },
  {
    "id": "l2d-models-615c42add339-d5e20b8e69ef",
    "name": "Mao",
    "family": "碧蓝航线",
    "version": "509d0facabef",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-d5e20b8e69ef/509d0facabef/model.moc3",
      "size": 879680,
      "sha1": "080583697cb9430ad0f0e7a33623674e69de6778"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-d5e20b8e69ef/509d0facabef/texture-0.png",
        "size": 3130953,
        "sha1": "e629e2a2b194c968b2af7107be654b02d7d74c26"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-d5e20b8e69ef/509d0facabef/preview.png",
      "size": 50278,
      "sha1": "f4fff2b7b764628adced5c38b1833ea0694d07a0"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-d5e20b8e69ef.jpg"
  },
  {
    "id": "l2d-models-615c42add339-5ccff8b47908",
    "name": "Mark",
    "family": "碧蓝航线",
    "version": "292ca56a36b4",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-5ccff8b47908/292ca56a36b4/model.moc3",
      "size": 124736,
      "sha1": "9f230c543f6d6952d975418580b591f94a656528"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-5ccff8b47908/292ca56a36b4/texture-0.png",
        "size": 465924,
        "sha1": "694c98775cb0fc66c5b0e41f8aaacbe61f6e707a"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-5ccff8b47908/292ca56a36b4/preview.png",
      "size": 23820,
      "sha1": "762a99d968d3f160fd6a051b3aca1c1c6b5ee48e"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-5ccff8b47908.jpg"
  },
  {
    "id": "l2d-models-615c42add339-0e21773e5820",
    "name": "Natori",
    "family": "碧蓝航线",
    "version": "ba868b54a7f8",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-0e21773e5820/ba868b54a7f8/model.moc3",
      "size": 771072,
      "sha1": "6ed8269b8cc4e7bbd4d344be64cd1b89fca96212"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-0e21773e5820/ba868b54a7f8/texture-0.png",
        "size": 2492342,
        "sha1": "af780b47f01dddea542c579f1375b90cf01227c8"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-0e21773e5820/ba868b54a7f8/preview.png",
      "size": 35182,
      "sha1": "f69569064f9cff23e2e9533e09e3f0703d7da6ce"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-0e21773e5820.jpg"
  },
  {
    "id": "l2d-models-615c42add339-f93383dab0f7",
    "name": "Rice",
    "family": "碧蓝航线",
    "version": "5c38c03d9bd6",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-f93383dab0f7/5c38c03d9bd6/model.moc3",
      "size": 479104,
      "sha1": "c56f4e0593c7a7a65f6a4c945f7e6645eae9e655"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-f93383dab0f7/5c38c03d9bd6/texture-0.png",
        "size": 1061518,
        "sha1": "d3d7711e1387a21474e4552accf78e4b0879fbee"
      },
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-f93383dab0f7/5c38c03d9bd6/texture-1.png",
        "size": 1505136,
        "sha1": "a86d059286d1d57979697633841438717c728462"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-f93383dab0f7/5c38c03d9bd6/preview.png",
      "size": 11868,
      "sha1": "0fa7803826ba73ecbfa8be0c752bde21643da25e"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-f93383dab0f7.jpg"
  },
  {
    "id": "l2d-models-615c42add339-a84f7b102e36",
    "name": "Senko_Normals · senko",
    "family": "碧蓝航线",
    "version": "36dcbaf5c31a",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-a84f7b102e36/36dcbaf5c31a/model.moc3",
      "size": 1665088,
      "sha1": "1ac5caad2ff449eb1f4c63b5c8edef77061d7a8b"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-a84f7b102e36/36dcbaf5c31a/texture-0.png",
        "size": 6235345,
        "sha1": "4742751026b4d71f923523ba8ad438e29115035e"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-a84f7b102e36/36dcbaf5c31a/preview.png",
      "size": 27749,
      "sha1": "6efca47d5e2ab774d0c37bfafd0d72f3698a031d"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-a84f7b102e36.jpg"
  },
  {
    "id": "l2d-models-615c42add339-48b359b44310",
    "name": "Wanko",
    "family": "碧蓝航线",
    "version": "b944b36adc5c",
    "model": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-48b359b44310/b944b36adc5c/model.moc3",
      "size": 107456,
      "sha1": "a2405100569eac44c2887ebddc70d99efbcb298b"
    },
    "textures": [
      {
        "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-48b359b44310/b944b36adc5c/texture-0.png",
        "size": 566299,
        "sha1": "adb1e4f25ca26c2324859040719290ec01f9a84d"
      }
    ],
    "preview": {
      "cloudPath": "ning/avatars/v1/l2d-models-615c42add339-48b359b44310/b944b36adc5c/preview.png",
      "size": 20078,
      "sha1": "08cd9a65f7c698b4d13acbd97a0193fb682a8559"
    },
    "localPreview": "/packages/avatars/previews/l2d-models-615c42add339-48b359b44310.jpg"
  }
];
